// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnun6EytCs2QVHpq9uYyROVqOvOdXI9ck',
    appId: '1:314803424918:web:f828a5c6572f884fb5bcb7',
    messagingSenderId: '314803424918',
    projectId: 'ujian-38585',
    authDomain: 'ujian-38585.firebaseapp.com',
    storageBucket: 'ujian-38585.firebasestorage.app',
    measurementId: 'G-WB5BEGBMJJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMmbWzUt8uvI8BOcgkQYvskuCqgFwQgBY',
    appId: '1:314803424918:android:55d88cb065c3092ab5bcb7',
    messagingSenderId: '314803424918',
    projectId: 'ujian-38585',
    storageBucket: 'ujian-38585.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0nY4C81mSnjEU7OLkaUf_UTnhXwOLe_c',
    appId: '1:314803424918:ios:806efedcd8ec33c7b5bcb7',
    messagingSenderId: '314803424918',
    projectId: 'ujian-38585',
    storageBucket: 'ujian-38585.firebasestorage.app',
    iosBundleId: 'com.example.projectUprak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0nY4C81mSnjEU7OLkaUf_UTnhXwOLe_c',
    appId: '1:314803424918:ios:806efedcd8ec33c7b5bcb7',
    messagingSenderId: '314803424918',
    projectId: 'ujian-38585',
    storageBucket: 'ujian-38585.firebasestorage.app',
    iosBundleId: 'com.example.projectUprak',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnun6EytCs2QVHpq9uYyROVqOvOdXI9ck',
    appId: '1:314803424918:web:288e6c77d464be25b5bcb7',
    messagingSenderId: '314803424918',
    projectId: 'ujian-38585',
    authDomain: 'ujian-38585.firebaseapp.com',
    storageBucket: 'ujian-38585.firebasestorage.app',
    measurementId: 'G-J5XWN6VNPG',
  );
}
